version: '3.1'

services:
  db:
    image: postgres
    command: -c fsync=off
    restart: unless-stopped
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: no_pass
      POSTGRES_DB: dz_dialect_training
